name: jrpn16c
description: Jovial RPN, a calculator simulator inspired by the HP-16C "Computer Scientist" Calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jrpn: 
    path: ../

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  msix: ^2.0.0

flutter_icons:
  image_path: assets_16/icon256.png
  image_path_ios:  assets_16/icon_ios.png
  android: true
  macos: true
  linux: true
  ios: true
  windows: true
  # If changed, "flutter pub run flutter_launcher_icons:main"
  # See https://pub.dev/packages/flutter_launcher_icons

flutter:
  uses-material-design: true
  assets:
    - assets/jupiter.si
  fonts:
    - family: KeyLabelFont
      fonts:
          - asset: fonts/deja_vu_sans.ttf
            style: normal
            weight: 400
          - asset: fonts/deja_vu_sans_bold.ttf
            style: normal
            weight: 700
    - family: LogoFont
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/WorkSans-Medium.ttf
          style: normal
          weight: 500
