
include: package:flutter_lints/flutter.yaml

linter:
    rules:
        unawaited_futures: true
        omit_local_variable_types: false
        public_member_api_docs: false
        avoid_types_on_closure_parameters: false
        camel_case_types: true
        cancel_subscriptions: true
        comment_references: true
        await_only_futures: true
        exhaustive_cases: true

analyzer:
    language:
        strict-casts: true
        strict-inference: true
        strict-raw-types: true
#   exclude:
#     - path/to/excluded/files/**
