name: jrpn
description: Jovial RPN, a calculator simulator inspired by the HP-16C "Computer Scientist" Calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+11

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  meta: ^1.7.0
  share_plus: ^6.3.0
  uni_links: ^0.5.1
  uni_links_web: ^0.1.0
  archive: ^3.1.2
  url_launcher: ^6.0.3
  file_selector: ^0.9.2
  desktop_multi_window:
    git:
      url: https://github.com/zathras/tmp_desktop_multi_window.git
      path: packages/desktop_multi_window
      ref: main
  vector_math: ^2.1.0
  jovial_svg: ^1.0.2
  jovial_misc: ^0.8.5

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  msix: ^3.6.2
# jrpn15:
#   path: '../jrpn15'
# jrpn16:
#   path: '../jrpn16'

flutter:
  uses-material-design: true
  assets:
    - assets/jupiter.si
    - assets/NAFO_OFAN_brain_damaged_cartoon_dogs.jpeg
    - assets/Тризуб.si
