name: jrpn
description: Jovial RPN, a calculator simulator inspired by the HP-16C "Computer Scientist" Calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  share_plus: ^2.0.2
  uni_links: ^0.5.1
  uni_links_web: ^0.1.0
  archive: ^3.1.2
  url_launcher: ^6.0.3
  jovial_svg: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  msix: ^2.0.0
  jrpn16c:
    path: '16c'

flutter:
  uses-material-design: true
  assets:
    - assets/jupiter.si
