name: jrpn15
base: core18
version: '2.1.0-beta'
summary: Simulator inspired by the HP-15C Scientific Calculator
description: |
  Calculator simulator inspired by the HP-15C scientific calculator.
  Written in Flutter, so UI scales to any screen size, and the same
  code is used for versions for Android, MacOS and Windows.
  store.

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict

build-packages:
    - dirmngr

apps:
    jrpn15:
        command: jrpn15
        extensions: [flutter-master]

parts:
    jrpn15:
        plugin: flutter
        source: .
        flutter-target: lib/main.dart
