name: jrpn15
description: Jovial RPN 15C Beta, a calculator simulator inspired by the HP-15C "Computer Scientist" Calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+8  # See also lib/generic_main.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  jrpn:
    git:
      url: https://github.com/zathras/jrpn.git
      path: shared
      ref: main
    # path: ../shared/
  meta: ^1.7.0
  shared_preferences: ^2.0.5
  share_plus: ^6.3.0
  desktop_multi_window: ^0.2.0
  file_selector: ^0.9.2
  uni_links: ^0.5.1
  uni_links_web: ^0.1.0
  archive: ^3.1.2
  url_launcher: ^6.0.3
  vector_math: ^2.1.0
  jovial_svg: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  msix: ^3.7.0

flutter_icons:
  image_path: "assets_15/icon256.png"
  image_path_ios:  assets_15/icon_ios.png
  android: 
    generate: true
  macos:
    generate: true
    image_path: "assets_15/icon256_macos.png"
  linux:
    generate: true
  windows: 
    generate: true
  # Left off: ios: generate: true 
  # If changed, "flutter pub run flutter_launcher_icons"
  # See https://pub.dev/packages/flutter_launcher_icons

flutter:
  uses-material-design: true
  fonts:
    - family: KeyLabelFont
      fonts:
          - asset: packages/jrpn/fonts/deja_vu_sans.ttf
            style: normal
            weight: 400
          - asset: packages/jrpn/fonts/deja_vu_sans_bold.ttf
            style: normal
            weight: 700
    - family: LogoFont
      fonts:
        - asset: packages/jrpn/fonts/WorkSans-Regular.ttf
          style: normal
          weight: 400
        - asset: packages/jrpn/fonts/WorkSans-Medium.ttf
          style: normal
          weight: 500
    - family: LiberationMono
      fonts:
        - asset: packages/jrpn/fonts/LiberationMono.ttf
          style: normal
          weight: 400
