
# See https://github.com/subosito/flutter-action

name:  Android APK Build
run-name: ${{ github.actor }} Android APK Build
on: 
    workflow_dispatch:          # Manually

    # push:
    #     branches: [master]
    #     paths-ignore:
    #         - '**/README.md'

jobs:
    jrpn-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: '11'
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  # flutter:version: '3.0.0'
            - run: |
                cd jrpn15
                flutter pub get
                sudo apt-get update -y
                sudo apt-get install -y ninja-build libgtk-3-dev
                flutter config --enable-android
                flutter build apk
            - uses: actions/android-sign@v1.2.2
              name: Sign 15c
              with:
                releaseDirectory: jrpn15/build/app/outputs/flutter-apk
                signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
                output: jrpn15/build/app/outputs/signed
                alias: ${{ secrets.ALIAS }}
                keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
            - run: |
                cd jrpn15/build/app/outputs/signed
                mv app-release.apk jrpn15_app-release.apk
            - uses: actions/upload-artifact@v3
              with:
                name:  jrpn15_android_apk
                path:  jrpn15/build/app/outputs/signed/jrpn15_app-release.apk
            - run: |
                cd jrpn16
                flutter pub get
                flutter build apk
            - run: |
                cd jrpn16/build/app/outputs/flutter-apk
                mv app-release.apk jrpn16_app-release.apk
            - run: |
                ls -ls ~/.android
                base64 ~/.android/debug.keystore
            - uses: actions/upload-artifact@v3
              with:
                name:  jrpn16_android_apk
                path:  jrpn16/build/app/outputs/flutter-apk/jrpn16_app-release.apk
