
# See https://github.com/subosito/flutter-action

name:  Experimment
run-name: ${{ github.actor }} experiment
on: 
    workflow_dispatch:          # Manually

    # push:
    #     branches: [master]
    #     paths-ignore:
    #         - '**/README.md'

jobs:
    macos-build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  architecture: x64
                  # flutter:version: '3.0.0'
            - run: flutter pub get
            - run: flutter build ios --help
